kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: jenkins-agent
  labels:
    labels: gcp-packer
    name: jenkins
    role: agent
spec:
  replicas: 1
  selector:
    labels: gcp-packer
    name: jenkins
    role: agent
  template:
    metadata:
      name: jenkins-agent
      labels:
        labels: gcp-packer
        name: jenkins
        role: agent
    spec:
      containers:
        - name: jenkins-agent
          image: 'gcr.io/epsilon-jenkins/jenkins-agent:latest'
          command:
            - sh
            - '-c'
            - '/usr/local/bin/jenkins-docker-supervisor.sh -master http://$JENKINS_SERVICE_HOST:$JENKINS_SERVICE_PORT_UI -tunnel $JENKINS_SERVICE_HOST:$JENKINS_SERVICE_PORT_DISCOVERY -executors 1 -labels gcp-packer'
          privileged: true
          volumeMounts:
            - name: settings
              mountPath: /home/jenkins-agent/.m2/
              readOnly: false
      volumes:
        - name: settings
          secret:
            secretName: maven-settings
