kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: jenkins-leader
  labels:
    name: jenkins
    role: leader
spec:
  replicas: 1
  selector:
    name: jenkins
    role: leader
  template:
    metadata:
      name: jenkins-leader
      labels:
        name: jenkins
        role: leader
    spec:
      containers:
        - name: jenkins
          image: 'gcr.io/epsilon-jenkins/jenkins-master:latest'
          command:
            - /usr/local/bin/start.sh
          ports:
            - name: jenkins-http
              containerPort: 8080
              protocol: TCP
            - name: jenkins-discovery
              containerPort: 50000
              protocol: TCP
          env:
            - name: GCS_RESTORE_URL
              value: 'gs://epsilon-jenkins-backup/LATEST.tar.gz'
