kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: ssl-proxy-secret
      containers:
        - name: nginx-ssl-proxy
          image: 'gcr.io/cloud-solutions-images/nginx-ssl-proxy:latest'
          command:
            - /bin/bash
            - /usr/bin/start.sh
          ports:
            - name: nginx-ssl-proxy-http
              containerPort: 80
              protocol: TCP
            - name: nginx-ssl-proxy-https
              containerPort: 443
              protocol: TCP
          env:
            - name: SERVICE_HOST_ENV_NAME
              value: JENKINS_SERVICE_HOST
            - name: SERVICE_PORT_ENV_NAME
              value: JENKINS_SERVICE_PORT_UI
            - name: ENABLE_SSL
              value: 'false'
            - name: ENABLE_BASIC_AUTH
              value: 'true'
          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: /etc/secrets
