kind: Service
apiVersion: v1beta3
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  ports:
    - name: https
      port: 443
      targetPort: nginx-ssl-proxy-https
    - name: http
      protocol: TCP
      port: 80
      targetPort: nginx-ssl-proxy-http
  selector:
    name: nginx
    role: ssl-proxy
  createExternalLoadBalancer: true
