kind:   Service
apiVersion:   v1
metadata:
  name: __serviceName__
  labels:
    name:   __serviceName__
    major:  "__major__"
spec:
  ports:
    - port:       __publicPort__
      targetPort: __privatePortName__
      protocol:   "TCP"
  selector:
    name:   __rcName__
    major:  "__major__"
    minor:  "__minor__"
    build:  "__build__"
